### PR TITLE
SickChill Windows Developer Installation & Setup Guide

### PR DESCRIPTION
**Pull request by daviegravy**
New to Git.  Trying to submit a new wiki page to help new developers on Windows platforms get setup and operate the SickChill development instance.

### CODE REVIEW

**Comment by BKSteve** [comment]
Made it an `.md` file and adjust format to be a mark down file consistent with others.

**Comment by BKSteve** [comment]
Where / how should this be linked into from the main page?

**Comment by daviegravy** [comment]
I think we should have a new Development main category.  This document could be under a broader sub-category called Frontend or even based on the main application versions of SickChill.  I imagine we will grow development documentation both frontend and backend development depending on future programmer commitment.  @miigotu can advise specifically as we have just begun the ideas of revamping the UI.

**Comment by BKSteve** [comment]
Temporarily it is under installation guides. 
My personal opinion is the wiki is for users and newbies and that developers wouldn't be using it.

**Comment by miigotu** [comment]
There should still be a developer guide, whether that is on the wiki or contributing.md. It shouldn't be black magic for a new contributor to figure out how to set up our development environment to be able to help. Previously, it was easy to help. Now with several layers of tools, multiple languages and differences between operating systems it has become necessary. 

I don't think it should be in installation guides, we shouldn't mix it with user documentation. It should be a separate section very clearly marked as developer guides, for development only. That way we don't confuse Darwin.

**Comment by BKSteve** [comment]
New links and page created. Sidebar too

**Pull request merged**
