### PR TITLE
Jackett Integration with SickChill

### PR DESCRIPTION
**Pull request by daviegravy**
Full step-by-step tutorial on installing and configuring Jackett and integrating Jackett into Sickchill.  Complete with screenshots and detailed explanations.

### CODE REVIEW

**Comment by daviegravy** [comment]
@BKSteve Can you help me understand how to get my tutorial added to the Wiki.  It should be a great addition for the configuration guides section.  I'm sorry if I didn't prepare this pull request correctly.  I'm not much familiar with git.

**Comment by BKSteve** [comment]
I will clone it into the main wiki as I accepted it into here so people can be initially directed here.
A bit busy the next day or 2 to properly check and integrate

**Comment by daviegravy** [comment]
@BKSteve  No worries.  I actually didn't know exactly what happened to it or that maybe I added something funky with the pull request.  Just let me know if a different format works better and I'll supply that instead of the .pdf - Thanks.

**Comment by BKSteve** [comment]
@daviegravy can you attach your file here, I can't get it from the pull request.
What's the source file as the wiki works on `mark down`

**Comment by daviegravy** [comment]
@BKSteve I created it on google docs.  It lets me export as docx, odt, rtf, pdf, txt, etc.  Here's a docx copy if that helps any.  Just let me know otherwise.
[Integrating Jackett & SickChill.docx](https://github.com/SickChill/SickChill.WikiTemp/files/11683930/Integrating.Jackett.SickChill.docx)

**Comment by BKSteve** [comment]
I'm thinking to link this in here https://github.com/SickChill/SickChill/wiki/Settings-explained#search-providers
With some simple text and a link to the extra pack specific to Jacket.
You want to amend the docx?

**Comment by BKSteve** [comment]
# **How to use Jackett with SickChill**

1. Go to [https://github.com/Jackett/Jackett](https://github.com/Jackett/Jackett) and look for the installation instructions and download for your OS of choice.
  1. Make sure to install Jackett as a service.
  2. Once the installation is finished, Navigate your web browser to[http://127.0.0.1:9117](http://127.0.0.1:9117/)
2. Begin by adding some trackers of your favorite or interesting providers by clicking on the **Add Indexer** button located towards the top.



**Note** : For your 1st time, filter by **public** and **en-US** trackers.

1. Add individual trackers by clicking the **blue wrench** button. This will open another box displaying the site details as well as all the categories that will be available through that tracker. Click the **Okay** button to finish adding the tracker to Jackett.





**Note** : Semi-private and private trackers will have additional details like cookies, usernames and/or passwords as well as site-specific API keys to use their trackers. If you don't have these details, don't add those trackers.

1. The tracker you added should now show up under your Jackett main window, Configured Indexers. You will want to click **Test** and verify Jackett reports successfully if it can communicate with the tracker. A green check indicates successful communication.



1. We are now ready to go over to SickChill and add Jackett. Leave Jackett open as we will need to click the **Copy Torznab Feed** button highlighted up top to copy the URL SickChill needs to our clipboard. We need to modify this URL Jackett gives us just a bit to take FULL advantage of Jackett.

**Note** : For easy reference, if you have Jackett installed on the same computer as SickChill, you can refer to the below for your provider site URL:

[**http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab/**](http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab/)

**IMPORTANT** : The key difference is we replaced the tracker specific directory in the URL with the keyword "all" - This ensures Jackett will provide SickChill ALL your trackers' results instead of just the one you copied the URL from.

1. We also need the API key listed in the upper right hand corner of Jackett as so. You can click to copy that to your clipboard when needed as well:



1. Navigate to your SickChill **Search Settings** , by clicking the **gears** icon in the upper right hand corner, then click on the **NZB Search** tab.
2. Check the box to **enable NZB search providers**. Leave default 500 for retention and Black hole for Send .nzb files to.
3. Set the **black hole folder location** to your directory where your torrent client downloads to. **Note** : This directory setting is not necessary for Jackett to work as long as SickChill is configured to communicate to your download client (qbittorrent, etc), but previous tutorials suggested setting this directory.





Make sure to click **Save Changes**!

**IMPORTANT** : It is assumed your SickChill application is already configured to communicate with your download client such as qbittorent, utorrent, deluge, etc.) If you haven't done so, please visit [https://github.com/SickChill/sickchill/wiki/Settings-explained](https://github.com/SickChill/sickchill/wiki/Settings-explained) and scroll down to the section on Torrent Search.

1. Now click on the **Search Providers** pill link on the navigation bar of SickChill and go to the (newly added if NZB wasn't previously enabled in SC) **Configure Custom Newsnab Provider** and click the drop-down to **- - add new provider - -**
2. Set the provider name as **Jackett**.
3. Go back to Jackett and copy the **Torznab Feed** url. **IMPORTANT** : If you copy from Jackett, we need to replace a part of the URL path with the "all" keyword instead of the tracker specific name you copied from. This ensures this one provider in SC will search ALL your providers in Jackett. Refer to the image below. 

For clarification purposes, if you have Jackett and SickChill installed on the same computer you can just copy and paste the below into your site URL for a hassle-free setup.

[http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab/](http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab/)

1. Now go and copy the **Jackett API** to your clipboard in the upper right hand corner of Jackett and paste that into the API key in the SC box accordingly.
2. Click **Add**. Now the categories will appear. Either individually select categories you want SC to search in Jackett by holding down Ctrl + click. Or just click in the box and select all (Ctrl+A) and click **Update Categories**. You should see the numerical category populate in the right side box for every category you successfully added.
3. Click to **Save Changes**!
4. Now go to the **Provider Priorities** tab in SC and select your newly added provider from the drop down.
5. Your new provider you added should be at the bottom of the list. Click and drag him up to the top. 

1. Now click on the **Provider Options** tab and select your newly added provider Jackett from the drop-down list and check both **enable daily searches** and **enable backlog searches** and any other settings displayed on this screen.
2. Click to **Save Changes**!
3. You are all done!
4. To test and ensure you are operational. Go to SickChill and manually search for an episode. Visit the logs in SC and ensure you see a search kick off named under your newly added provider name:

2023-06-03 23:15:06 INFO :: SEARCHQUEUE-MANUAL-353546 :: [Jackett (ALL)] :: Performing episode search for \<show\_name\> (\<year\>)

1. Go over to the Jackett UI and click on **view logs** under the Jackett Configuration, you should see your SC search request details in the log and whether Jackett found relevant releases that match:





If you have any issues at this point, simply jump over to the SickChill discord chat for some friendly support by visiting [https://discord.gg/FXre9qkHwE](https://discord.gg/FXre9qkHwE)

Version 1.0 - Last Updated: 6/4/2023

**Comment by BKSteve** [comment]
Pulled in take a look.
https://github.com/SickChill/SickChill.WikiTemp/blob/main/Settings-jackett.md

**Comment by daviegravy** [comment]
@BKSteve It looks great! - Thank you for adding the content and making the necessary modifications to the .md filetype.  Much appreciated!

**Pull request closed without merging**
